name: 'migration'
on:
  workflow_dispatch: {}
  pull_request:
    types: [ labeled, opened, synchronize, reopened ]

jobs:
  build:
    if: ${{ github.event.label.name == 'migration' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
        with:
          repository: arangodb/docs
          path: ./docs-old
          submodules: recursive

      - uses: actions/checkout@master
        with:
          repository: arangodb/arangodb
          path: ./arangodb-main
          submodules: recursive

      - uses: actions/checkout@master
        with:
          repository: arangodb/docs-hugo
          path: ./docs-hugo
          submodules: recursive

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: pip install pyyaml
      - run: python /home/runner/work/docs-hugo/docs-hugo/docs-hugo/migration-tools/migration/migration.py --src /home/runner/work/docs-hugo/docs-hugo/docs-old --dst /home/runner/work/docs-hugo/docs-hugo/docs-hugo --arango-main /home/runner/work/docs-hugo/docs-hugo/arangodb-main --version 3.10
      - run: python /home/runner/work/docs-hugo/docs-hugo/docs-hugo/migration-tools/migration/migration.py --src /home/runner/work/docs-hugo/docs-hugo/docs-old --dst /home/runner/work/docs-hugo/docs-hugo/docs-hugo --arango-main /home/runner/work/docs-hugo/docs-hugo/arangodb-main --version 3.11
      - run: bash /home/runner/work/docs-hugo/docs-hugo/docs-hugo/migration-tools/migration/restructure.sh
      
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
            hugo-version: 'latest'

      - name: Build
        run: cd docs-hugo/site && hugo -b https://deploy-preview-${{ github.event.number }}--startling-truffle-6032f2.netlify.app --minify -e prod

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=docs-hugo/site/public --alias deploy-preview-${{ github.event.number }}--
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

        

      