name: 'plain-build-deploy'
on:
  workflow_dispatch: {}
  pull_request:
    types: [ labeled, opened, synchronize, reopened ]

jobs:
  build:
    if: ${{ (github.event.label.name != 'examples-generation') && (github.event.label.name != 'migration') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Step 2 - Sets up the latest version of Hugo
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
            hugo-version: 'latest'

      # Step 4 - Builds the site using the latest version of Hugo
      # Also specifies the theme we want to use
      - name: Build
        run: cd site && hugo -b https://deploy-preview-${{ github.event.number }}--startling-truffle-6032f2.netlify.app --minify -e prod

      - name: Deploy to netlify
        uses: netlify/actions/cli@master
        id: deploy
        with:
          args: deploy --dir=site/public --alias deploy-preview-${{ github.event.number }}--
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          GITHUB_OUTPUT: ${{ steps.deploy.NETLIFY_URL }}
          
      - name: Adding markdown
        run: echo ‘### Hello world! :rocket:’ >> $GITHUB_STEP_SUMMARY


        

      